/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and checked in here so jsconfig typecheck
// works before the first local `next dev` run.
